/* =========================================================
   Algeria Pulse — Configuration & Bilingual Datasets
   Global constants: the full EN/AR translation dictionary,
   the language cycle order, and the hashtag catalog (including
   the localized default #Pulse / #نبضة tag).
   ========================================================= */

export const I18N = {
  en: {
    app_title: "Algeria Pulse",
    app_subtitle: "Share what's happening, wilaya by wilaya.",
    select_province: "Select your wilaya",
    select_placeholder: "Choose a wilaya…",
    notice_title: "Before you post",
    notice_body: "Please note that Law No. 09-04 of August 5, 2009, is in force in Algeria. This law stipulates strict sanctions against any online publication that may disturb public order or violate applicable regulations. To avoid any legal consequences, please comply with this legislation and refrain from sharing harmful, illegal, or violence-inciting content.",
    write_label: "Your idea, event, or news",
    write_placeholder: "What's happening in your wilaya?",
    map_label: "Tap a wilaya on the map",
    output_label: "Shareable link",
    output_placeholder: "Your link will appear here…",
    footer_developed: "Developed with",
    footer_by: "by",
    copied: "Link copied to clipboard!",
    copy_failed: "Couldn't copy — select and copy manually.",
    need_input: "Pick a wilaya and write something first.",
    shared_banner: "Viewing a shared pulse",
    about_title: "About Algeria Pulse",
    about_lead: "Algeria Pulse is a lightweight, serverless way to turn a local idea, event, or breaking story into a link you can send anywhere — no account, no backend, no data storage.",
    about_step1_title: "1. Pick a wilaya",
    about_step1_body: "Choose your province from the dropdown or tap it directly on the interactive map.",
    about_step2_title: "2. Write your pulse",
    about_step2_body: "Type your idea, event, or news update in the text field, in Arabic or English — tap the expand icon for a bigger writing space with live counts.",
    about_step3_title: "3. Tag it",
    about_step3_body: "Every pulse carries the #Pulse tag by default — add a preset like Urgent or Traffic, or type your own.",
    about_step4_title: "4. Get your link",
    about_step4_body: "Once a wilaya, a message, and a tag are all in place, a unique link is generated instantly.",
    about_step5_title: "5. Share it anywhere",
    about_step5_body: "Copy the link, copy a ready-made snippet, or share it directly — Algeria Pulse never stores your content.",
    feature_privacy: "100% client-side, zero server storage",
    feature_bilingual: "Full Arabic / English support",
    feature_theme: "Light & dark Green Forest theme",
    feature_map: "Interactive 58-wilaya map",
    feature_identity: "Tap your name or avatar to edit it",
    feature_tags: "Preset & custom hashtags",
    feature_map_expand: "Expand the map to full screen",
    feature_breakdown: "See exactly what's inside your link",
    about_nav_aria: "About Algeria Pulse",
    metric_user_label: "User",
    metric_time_label: "Participated",
    metric_no_user: "—",
    modal_title: "What should we call you?",
    modal_sub: "Your name is included in the link you generate.",
    modal_placeholder: "Enter a username…",
    modal_submit: "Continue",
    modal_error: "Please enter at least 2 characters.",
    modal_title_edit: "Update your username",
    modal_sub_edit: "This changes the name used in links you generate from now on.",
    edit_username_aria: "Edit username",
    modal_anonymous: "Continue as Anonymous",
    anonymous_label: "Anonymous",
    new_idea_aria: "Start a new idea",
    new_idea_fab_label: "New idea",
    feed_nav_aria: "Your local feed",
    feed_close_aria: "Close",
    feed_title: "Your local feed",
    feed_sub: "Pulses you've created or viewed, saved only on this device.",
    feed_search_placeholder: "Search your feed…",
    feed_filter_all: "All",
    feed_filter_mine: "Mine",
    feed_filter_viewed: "Viewed",
    feed_empty: "Nothing saved yet — pulses you create or open will show up here.",
    feed_empty_filtered: "Nothing matches that search or filter.",
    feed_clear: "Clear local feed",
    feed_clear_confirm: "Tap again to confirm",
    feed_badge_created: "Yours",
    feed_badge_viewed: "Viewed",
    feed_saved_toast: "Saved to your local feed",
    feed_cleared_toast: "Local feed cleared",
    feed_deleted_toast: "Removed from your local feed",
    copy_snippet_aria: "Copy formatted snippet",
    snippet_copied: "Snippet copied to clipboard!",
    relative_just_now: "just now",
    metric_chars: "chars",
    metric_words: "words",
    metric_lines: "lines",
    expand_editor_aria: "Expand editor",
    expand_editor_title: "Write comfortably",
    tags_label: "Tags",
    custom_tag_placeholder: "Add your own tag…",
    add_tag_aria: "Add tag",
    ticker_empty: "Your local feed will appear here as you create or open pulses."
  },
  ar: {
    app_title: "نبض الجزائر",
    app_subtitle: "شارك ما يحدث في كل ولاية.",
    select_province: "اختر ولايتك",
    select_placeholder: "اختر ولاية…",
    notice_title: "قبل أن تنشر",
    notice_body: "يرجى العلم أن القانون رقم 09-04 المؤرخ في 5 أوت 2009 ساري المفعول في الجزائر. ينص هذا القانون على عقوبات صارمة ضد كل نشر إلكتروني من شأنه الإخلال بالنظام العام أو مخالفة الأنظمة المعمول بها. تجنبًا لأي تبعات قانونية، يرجى الالتزام بهذا التشريع والامتناع عن مشاركة محتوى ضار أو غير قانوني أو محرّض على العنف.",
    write_label: "فكرتك أو الحدث أو الخبر",
    write_placeholder: "ما الذي يحدث في ولايتك؟",
    map_label: "اضغط على ولاية في الخريطة",
    output_label: "الرابط القابل للمشاركة",
    output_placeholder: "سيظهر رابطك هنا…",
    footer_developed: "طُوّر بـ",
    footer_by: "بواسطة",
    copied: "تم نسخ الرابط!",
    copy_failed: "تعذر النسخ — انسخ يدويًا.",
    need_input: "اختر ولاية واكتب شيئًا أولاً.",
    shared_banner: "أنت تشاهد نبضة مشتركة",
    about_title: "حول نبض الجزائر",
    about_lead: "نبض الجزائر أداة خفيفة لا تعتمد على أي خادم، تُحوّل فكرة أو حدثًا أو خبرًا محليًا إلى رابط يمكنك إرساله إلى أي مكان — بدون حساب، بدون خادم خلفي، وبدون تخزين بيانات.",
    about_step1_title: "١. اختر ولاية",
    about_step1_body: "اختر ولايتك من القائمة المنسدلة أو اضغط عليها مباشرة على الخريطة التفاعلية.",
    about_step2_title: "٢. اكتب نبضتك",
    about_step2_body: "اكتب فكرتك أو الحدث أو الخبر في حقل النص، بالعربية أو الإنجليزية — اضغط أيقونة التوسيع لمساحة كتابة أكبر مع عدادات مباشرة.",
    about_step3_title: "٣. أضف وسمًا",
    about_step3_body: "تحمل كل نبضة وسم #Pulse تلقائيًا — أضف وسمًا جاهزًا مثل عاجل أو مرور، أو اكتب وسمك الخاص.",
    about_step4_title: "٤. احصل على رابطك",
    about_step4_body: "بمجرد اختيار الولاية وكتابة الرسالة وإضافة وسم، يتم إنشاء رابط فريد فورًا.",
    about_step5_title: "٥. شاركه أينما شئت",
    about_step5_body: "انسخ الرابط، انسخ مقتطفًا جاهزًا، أو شاركه مباشرة — نبض الجزائر لا يخزّن محتواك أبدًا.",
    feature_privacy: "١٠٠٪ من جهة العميل، بدون تخزين على أي خادم",
    feature_bilingual: "دعم كامل للغتين العربية والإنجليزية",
    feature_theme: "وضع فاتح وداكن بطابع الغابة الخضراء",
    feature_map: "خريطة تفاعلية لـ ٥٨ ولاية",
    feature_identity: "اضغط على اسمك أو صورتك لتعديله",
    feature_tags: "وسوم جاهزة وأخرى مخصصة",
    feature_map_expand: "وسّع الخريطة لتملأ الشاشة",
    feature_breakdown: "اطّلع بدقة على محتوى رابطك",
    about_nav_aria: "حول نبض الجزائر",
    metric_user_label: "المستخدم",
    metric_time_label: "وقت المشاركة",
    metric_no_user: "—",
    modal_title: "بماذا نناديك؟",
    modal_sub: "يُدرج اسمك ضمن الرابط الذي تنشئه.",
    modal_placeholder: "أدخل اسم المستخدم…",
    modal_submit: "متابعة",
    modal_error: "الرجاء إدخال حرفين على الأقل.",
    modal_title_edit: "تحديث اسم المستخدم",
    modal_sub_edit: "سيُستخدم هذا الاسم في الروابط التي تنشئها من الآن فصاعدًا.",
    edit_username_aria: "تعديل اسم المستخدم",
    modal_anonymous: "المتابعة كمجهول",
    anonymous_label: "مجهول",
    new_idea_aria: "بدء فكرة جديدة",
    new_idea_fab_label: "فكرة جديدة",
    feed_nav_aria: "سجلّك المحلي",
    feed_close_aria: "إغلاق",
    feed_title: "سجلّك المحلي",
    feed_sub: "النبضات التي أنشأتها أو شاهدتها، محفوظة على جهازك فقط.",
    feed_search_placeholder: "ابحث في سجلّك…",
    feed_filter_all: "الكل",
    feed_filter_mine: "لي",
    feed_filter_viewed: "مُشاهَدة",
    feed_empty: "لا يوجد شيء محفوظ بعد — ستظهر هنا النبضات التي تنشئها أو تفتحها.",
    feed_empty_filtered: "لا توجد نتائج مطابقة لهذا البحث أو التصفية.",
    feed_clear: "مسح السجلّ المحلي",
    feed_clear_confirm: "اضغط مرة أخرى للتأكيد",
    feed_badge_created: "لك",
    feed_badge_viewed: "مُشاهَدة",
    feed_saved_toast: "تم الحفظ في سجلّك المحلي",
    feed_cleared_toast: "تم مسح السجلّ المحلي",
    feed_deleted_toast: "تم الحذف من سجلّك المحلي",
    copy_snippet_aria: "نسخ المقتطف المنسّق",
    snippet_copied: "تم نسخ المقتطف!",
    relative_just_now: "الآن",
    metric_chars: "حرف",
    metric_words: "كلمة",
    metric_lines: "سطر",
    expand_editor_aria: "توسيع المحرر",
    expand_editor_title: "اكتب بارتياح",
    tags_label: "الوسوم",
    custom_tag_placeholder: "أضف وسمك الخاص…",
    add_tag_aria: "إضافة وسم",
    ticker_empty: "سيظهر سجلّك المحلي هنا عند إنشاء أو فتح نبضات."
  }
};

// Cycle order for the language toggle button.
export const LANGUAGES = ["en", "ar"];

// Smart hashtags/tags catalog. Users can also add their own free-form
// tags via the custom tag input (see ui.js addCustomTag()).
export const TAGS = [
  { id: "urgent", en: "Urgent", ar: "عاجل" },
  { id: "alert", en: "Alert", ar: "تنبيه" },
  { id: "services", en: "Services", ar: "خدمات" },
  { id: "traffic", en: "Traffic", ar: "مرور" }
];

// Every pulse automatically carries this branded tag — it's pinned
// (always active, not user-removable) and alone satisfies the "at least
// one tag" requirement in the link-generation validation gate.
export const DEFAULT_TAG = "pulse";
export const DEFAULT_TAG_LABELS = { en: "Pulse", ar: "نبضة" };

